<a href="https://colab.research.google.com/github/Yogeshkumar170201/Machine-Learning/blob/main/Scrapping_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Scrapping**

In [ ]:
import requests

In [ ]:
from bs4 import BeautifulSoup

In [ ]:
url = "https://www.goodreads.com/quotes/tag/love?page={}"

In [ ]:
emotions = ["love", "life"]

In [ ]:
url.format("love")

'https://www.goodreads.com/quotes/tag/love?page=love'

In [ ]:
def get_quotes(url): 

  res = requests.get(url)

  soup = BeautifulSoup(res.text)

  quote_divs = soup.find_all("div", attrs={"class":"quote"})

  quotes = []

  for quote_div in quote_divs:

    quoteText_div = quote_div.find_next("div", attrs={"class":"quoteText"})
    
    striped = quoteText_div.text.strip()
    
    striped_li = striped.split("\n")
    
    quote = striped_li[0][1:-1]
    
    author = striped_li[-1].strip()

    left_div = quote_div.find_next("div", attrs={"class" : "left"})
    tags = [tag.text for tag in  left_div.find_all("a")]

    quote_item = {
        "text" : quote,
        "author" : author,
        "tags" : tags
    }
    quotes.append(quote_item)
    
  return quotes

You can add whole list using append while using append you can add only one item

In [ ]:
total = []
for i in range(1, 6):
  total.extend(get_quotes(url.format("love", i)))
  print("processed", i)

processed 1
processed 2
processed 3
processed 4
processed 5

In [ ]:
len(total)

150

In [ ]:
total

[{'author': 'Marilyn Monroe',
  'tags': ['attributed-no-source',
   'best',
   'life',
   'love',
   'mistakes',
   'out-of-control',
   'truth',
   'worst'],
  'text': "I'm selfish, impatient and a little insecure. I make mistakes, I am out of control and at times hard to handle. But if you can't handle me at my worst, then you sure as hell don't deserve me at my best."},
 {'author': 'William W. Purkey',
  'tags': ['dance', 'heaven', 'hurt', 'inspirational', 'life', 'love', 'sing'],
  'text': "You've gotta dance like there's nobody watching,Love like you'll never be hurt,Sing like there's nobody listening,And live like it's heaven on earth."},
 {'author': 'Dr. Seuss',
  'tags': ['attributed-no-source', 'dreams', 'love', 'reality', 'sleep'],
  'text': "You know you're in love when you can't fall asleep because reality is finally better than your dreams."},
 {'author': 'Elbert Hubbard',
  'tags': ['friend', 'friendship', 'knowledge', 'love'],
  'text': 'A friend is someone who knows all about you and still loves you.'},
 {'author': '//]]>',
  'tags': ['darkness',
   'drive-out',
   'hate',
   'inspirational',
   'light',
   'love',
   'peace'],
  'text': 'Darkness cannot drive out darkness: only light can do that. Hate cannot drive out hate: only love can do that.'},
 {'author': '//]]>',
  'tags': ['inspirational', 'love'],
  'text': 'We accept the love we think we deserve.'},
 {'author': '//]]>',
  'tags': ['life', 'love'],
  'text': 'It is better to be hated for what you are than to be loved for what you are not.'},
 {'author': 'Bob Marley',
  'tags': ['love'],
  'text': 'Only once in your life, I truly believe, you find someone who can completely turn your world around. You tell them things that you’ve never shared with another soul and they absorb everything you say and actually want to hear more. You share hopes for the future, dreams that will never come true, goals that were never achieved and the many disappointments life has thrown at you. When something wonderful happens, you can’t wait to tell them about it, knowing they will share in your excitement. They are not embarrassed to cry with you when you are hurting or laugh with you when you make a fool of yourself. Never do they hurt your feelings or make you feel like you are not good enough, but rather they build you up and show you the things about yourself that make you special and even beautiful. There is never any pressure, jealousy or competition but only a quiet calmness when they are around. You can be yourself and not worry about what they will think of you because they love you for who you are. The things that seem insignificant to most people such as a note, song or walk become invaluable treasures kept safe in your heart to cherish forever. Memories of your childhood come back and are so clear and vivid it’s like being young again. Colours seem brighter and more brilliant. Laughter seems part of daily life where before it was infrequent or didn’t exist at all. A phone call or two during the day helps to get you through a long day’s work and always brings a smile to your face. In their presence, there’s no need for continuous conversation, but you find you’re quite content in just having them nearby. Things that never interested you before become fascinating because you know they are important to this person who is so special to you. You think of this person on every occasion and in everything you do. Simple things bring them to mind like a pale blue sky, gentle wind or even a storm cloud on the horizon. You open your heart knowing that there’s a chance it may be broken one day and in opening your heart, you experience a love and joy that you never dreamed possible. You find that being vulnerable is the only way to allow your heart to feel true pleasure that’s so real it scares you. You find strength in knowing you have a true friend and possibly a soul mate who will remain loyal to the end. Life seems completely different, exciting and worthwhile. Your only hope and security is in knowing that they are a part of your life.'},
 {'author': '//]]>',
  'tags': ['love'],
  'text': 'As he read, I fell in love the way you fall asleep: slowly, and then all at once.'},
 {'author': 'Friedrich Nietzsche',
  'tags': ['friendship',
   'lack-of-friendship',
   'lack-of-love',
   'love',
   'marriage',
   'unhappy-marriage'],
  'text': 'It is not a lack of love, but a lack of friendship that makes unhappy marriages.'},
 {'author': 'Elie Wiesel',
  'tags': ['activism',
   'apathy',
   'hate',
   'indifference',
   'inspirational',
   'love',
   'opposite',
   'philosophy'],
  'text': "The opposite of love is not hate, it's indifference. The opposite of art is not ugliness, it's indifference. The opposite of faith is not heresy, it's indifference. And the opposite of life is not death, it's indifference."},
 {'author': '//]]>',
  'tags': ['love', 'poetry'],
  'text': 'I love you without knowing how, or when, or from where. I love you simply, without problems or pride: I love you in this way because I do not know any other way of loving but this, in which there is no I or you, so intimate that your hand upon my chest is my hand, so intimate that when I fall asleep your eyes close.'},
 {'author': '//]]>',
  'tags': ['do-wrong', 'love', 'trust', 'wrong'],
  'text': 'Love all, trust a few, do wrong to none.'},
 {'author': '//]]>',
  'tags': ['love'],
  'text': "Have you ever been in love? Horrible isn't it? It makes you so vulnerable. It opens your chest and it opens up your heart and it means that someone can get inside you and mess you up."},
 {'author': 'Lao Tzu',
  'tags': ['courage',
   'deeply-loved',
   'love',
   'strength',
   'widely-misattributed'],
  'text': 'Being deeply loved by someone gives you strength, while loving someone deeply gives you courage.'},
 {'author': 'Marilyn Monroe',
  'tags': ['attributed-no-source',
   'friends',
   'heartbreak',
   'inspirational',
   'life',
   'love',
   'sisters'],
  'text': "This life is what you make it. No matter what, you're going to mess up sometimes, it's a universal truth. But the good part is you get to decide how you're going to mess it up. Girls will be your friends - they'll act like it anyway. But just remember, some come, some go. The ones that stay with you through everything - they're your true best friends. Don't let go of them. Also remember, sisters make the best friends in the world. As for lovers, well, they'll come and go too. And baby, I hate to say it, most of them - actually pretty much all of them are going to break your heart, but you can't give up because if you give up, you'll never find your soulmate. You'll never find that half who makes you whole and that goes for everything. Just because you fail once, doesn't mean you're gonna fail at everything. Keep trying, hold on, and always, always, always believe in yourself, because if you don't, then who will, sweetie? So keep your head high, keep your chin up, and most importantly, keep smiling, because life's a beautiful thing and there's so much to smile about."},
 {'author': '//]]>',
  'tags': ['love'],
  'text': 'There is never a time or place for true love. It happens accidentally, in a heartbeat, in a single flashing, throbbing moment.'},
 {'author': '//]]>',
  'tags': ['essential', 'happiness', 'love'],
  'text': 'Love is that condition in which the happiness of another person is essential to your own.'},
 {'author': 'Bob Marley',
  'tags': ['love'],
  'text': "You may not be her first, her last, or her only. She loved before she may love again. But if she loves you now, what else matters? She's not perfect—you aren't either, and the two of you may never be perfect together but if she can make you laugh, cause you to think twice, and admit to being human and making mistakes, hold onto her and give her the most you can. She may not be thinking about you every second of the day, but she will give you a part of her that she knows you can break—her heart. So don't hurt her, don't change her, don't analyze and don't expect more than she can give. Smile when she makes you happy, let her know when she makes you mad, and miss her when she's not there."},
 {'author': '//]]>',
  'tags': ['katniss', 'love', 'peeta', 'suzanne-collins', 'the-hunger-games'],
  'text': 'You love me. Real or not real?"I tell him, "Real.'},
 {'author': '//]]>',
  'tags': ['doomed', 'inevitable', 'love', 'oblivion', 'pleasure', 'simple'],
  'text': 'I\'m in love with you," he said quietly."Augustus," I said."I am," he said. He was staring at me, and I could see the corners of his eyes crinkling. "I\'m in love with you, and I\'m not in the business of denying myself the simple pleasure of saying true things. I\'m in love with you, and I know that love is just a shout into the void, and that oblivion is inevitable, and that we\'re all doomed and that there will come a day when all our labor has been returned to dust, and I know the sun will swallow the only earth we\'ll ever have, and I am in love with you.'},
 {'author': '//]]>',
  'tags': ['love'],
  'text': "I am nothing special, of this I am sure. I am a common man with common thoughts and I've led a common life. There are no monuments dedicated to me and my name will soon be forgotten, but I've loved another with all my heart and soul, and to me, this has always been enough.."},
 {'author': '//]]>',
  'tags': ['love'],
  'text': 'Love looks not with the eyes, but with the mind,And therefore is winged Cupid painted blind.'},
 {'author': '//]]>',
  'tags': ['love', 'simile'],
  'text': "Love is like the wind, you can't see it but you can feel it."},
 {'author': '//]]>',
  'tags': ['love'],
  'text': "People think a soul mate is your perfect fit, and that's what everyone wants. But a true soul mate is a mirror, the person who shows you everything that is holding you back, the person who brings you to your own attention so you can change your life. A true soul mate is probably the most important person you'll ever meet, because they tear down your walls and smack you awake. But to live with a soul mate forever? Nah. Too painful. Soul mates, they come into your life just to reveal another layer of yourself to you, and then leave. A soul mates purpose is to shake you up, tear apart your ego a little bit, show you your obstacles and addictions, break your heart open so new light can get in, make you so desperate and out of control that you have to transform your life, then introduce you to your spiritual master..."},
 {'author': '//]]>',
  'tags': ['imperfect', 'love'],
  'text': "You don't love someone because they're perfect, you love them in spite of the fact that they're not."},
 {'author': '//]]>',
  'tags': ['friendship', 'love'],
  'text': 'There is nothing I would not do for those who are really my friends. I have no notion of loving people by halves, it is not my nature.'},
 {'author': 'Marilyn Monroe',
  'tags': ['attributed-no-source', 'girls', 'love'],
  'text': 'If you can make a woman laugh, you can make her do anything.'},
 {'author': 'Anais Nin',
  'tags': ['death', 'love'],
  'text': "Love never dies a natural death. It dies because we don't know how to replenish its source. It dies of blindness and errors and betrayals. It dies of illness and wounds; it dies of weariness, of witherings, of tarnishings."},
 {'author': '//]]>',
  'tags': ['love', 'weirdness'],
  'text': 'We’re all a little weird. And life is a little weird. And when we find someone whose weirdness is compatible with ours, we join up with them and fall into mutually satisfying weirdness—and call it love—true love.'},
 {'author': 'Marilyn Monroe',
  'tags': ['attributed-no-source',
   'best',
   'life',
   'love',
   'mistakes',
   'out-of-control',
   'truth',
   'worst'],
  'text': "I'm selfish, impatient and a little insecure. I make mistakes, I am out of control and at times hard to handle. But if you can't handle me at my worst, then you sure as hell don't deserve me at my best."},
 {'author': 'William W. Purkey',
  'tags': ['dance', 'heaven', 'hurt', 'inspirational', 'life', 'love', 'sing'],
  'text': "You've gotta dance like there's nobody watching,Love like you'll never be hurt,Sing like there's nobody listening,And live like it's heaven on earth."},
 {'author': 'Dr. Seuss',
  'tags': ['attributed-no-source', 'dreams', 'love', 'reality', 'sleep'],
  'text': "You know you're in love when you can't fall asleep because reality is finally better than your dreams."},
 {'author': 'Elbert Hubbard',
  'tags': ['friend', 'friendship', 'knowledge', 'love'],
  'text': 'A friend is someone who knows all about you and still loves you.'},
 {'author': '//]]>',
  'tags': ['darkness',
   'drive-out',
   'hate',
   'inspirational',
   'light',
   'love',
   'peace'],
  'text': 'Darkness cannot drive out darkness: only light can do that. Hate cannot drive out hate: only love can do that.'},
 {'author': '//]]>',
  'tags': ['inspirational', 'love'],
  'text': 'We accept the love we think we deserve.'},
 {'author': '//]]>',
  'tags': ['life', 'love'],
  'text': 'It is better to be hated for what you are than to be loved for what you are not.'},
 {'author': 'Bob Marley',
  'tags': ['love'],
  'text': 'Only once in your life, I truly believe, you find someone who can completely turn your world around. You tell them things that you’ve never shared with another soul and they absorb everything you say and actually want to hear more. You share hopes for the future, dreams that will never come true, goals that were never achieved and the many disappointments life has thrown at you. When something wonderful happens, you can’t wait to tell them about it, knowing they will share in your excitement. They are not embarrassed to cry with you when you are hurting or laugh with you when you make a fool of yourself. Never do they hurt your feelings or make you feel like you are not good enough, but rather they build you up and show you the things about yourself that make you special and even beautiful. There is never any pressure, jealousy or competition but only a quiet calmness when they are around. You can be yourself and not worry about what they will think of you because they love you for who you are. The things that seem insignificant to most people such as a note, song or walk become invaluable treasures kept safe in your heart to cherish forever. Memories of your childhood come back and are so clear and vivid it’s like being young again. Colours seem brighter and more brilliant. Laughter seems part of daily life where before it was infrequent or didn’t exist at all. A phone call or two during the day helps to get you through a long day’s work and always brings a smile to your face. In their presence, there’s no need for continuous conversation, but you find you’re quite content in just having them nearby. Things that never interested you before become fascinating because you know they are important to this person who is so special to you. You think of this person on every occasion and in everything you do. Simple things bring them to mind like a pale blue sky, gentle wind or even a storm cloud on the horizon. You open your heart knowing that there’s a chance it may be broken one day and in opening your heart, you experience a love and joy that you never dreamed possible. You find that being vulnerable is the only way to allow your heart to feel true pleasure that’s so real it scares you. You find strength in knowing you have a true friend and possibly a soul mate who will remain loyal to the end. Life seems completely different, exciting and worthwhile. Your only hope and security is in knowing that they are a part of your life.'},
 {'author': '//]]>',
  'tags': ['love'],
  'text': 'As he read, I fell in love the way you fall asleep: slowly, and then all at once.'},
 {'author': 'Friedrich Nietzsche',
  'tags': ['friendship',
   'lack-of-friendship',
   'lack-of-love',
   'love',
   'marriage',
   'unhappy-marriage'],
  'text': 'It is not a lack of love, but a lack of friendship that makes unhappy marriages.'},
 {'author': 'Elie Wiesel',
  'tags': ['activism',
   'apathy',
   'hate',
   'indifference',
   'inspirational',
   'love',
   'opposite',
   'philosophy'],
  'text': "The opposite of love is not hate, it's indifference. The opposite of art is not ugliness, it's indifference. The opposite of faith is not heresy, it's indifference. And the opposite of life is not death, it's indifference."},
 {'author': '//]]>',
  'tags': ['love', 'poetry'],
  'text': 'I love you without knowing how, or when, or from where. I love you simply, without problems or pride: I love you in this way because I do not know any other way of loving but this, in which there is no I or you, so intimate that your hand upon my chest is my hand, so intimate that when I fall asleep your eyes close.'},
 {'author': '//]]>',
  'tags': ['do-wrong', 'love', 'trust', 'wrong'],
  'text': 'Love all, trust a few, do wrong to none.'},
 {'author': '//]]>',
  'tags': ['love'],
  'text': "Have you ever been in love? Horrible isn't it? It makes you so vulnerable. It opens your chest and it opens up your heart and it means that someone can get inside you and mess you up."},
 {'author': 'Lao Tzu',
  'tags': ['courage',
   'deeply-loved',
   'love',
   'strength',
   'widely-misattributed'],
  'text': 'Being deeply loved by someone gives you strength, while loving someone deeply gives you courage.'},
 {'author': 'Marilyn Monroe',
  'tags': ['attributed-no-source',
   'friends',
   'heartbreak',
   'inspirational',
   'life',
   'love',
   'sisters'],
  'text': "This life is what you make it. No matter what, you're going to mess up sometimes, it's a universal truth. But the good part is you get to decide how you're going to mess it up. Girls will be your friends - they'll act like it anyway. But just remember, some come, some go. The ones that stay with you through everything - they're your true best friends. Don't let go of them. Also remember, sisters make the best friends in the world. As for lovers, well, they'll come and go too. And baby, I hate to say it, most of them - actually pretty much all of them are going to break your heart, but you can't give up because if you give up, you'll never find your soulmate. You'll never find that half who makes you whole and that goes for everything. Just because you fail once, doesn't mean you're gonna fail at everything. Keep trying, hold on, and always, always, always believe in yourself, because if you don't, then who will, sweetie? So keep your head high, keep your chin up, and most importantly, keep smiling, because life's a beautiful thing and there's so much to smile about."},
 {'author': '//]]>',
  'tags': ['love'],
  'text': 'There is never a time or place for true love. It happens accidentally, in a heartbeat, in a single flashing, throbbing moment.'},
 {'author': '//]]>',
  'tags': ['essential', 'happiness', 'love'],
  'text': 'Love is that condition in which the happiness of another person is essential to your own.'},
 {'author': 'Bob Marley',
  'tags': ['love'],
  'text': "You may not be her first, her last, or her only. She loved before she may love again. But if she loves you now, what else matters? She's not perfect—you aren't either, and the two of you may never be perfect together but if she can make you laugh, cause you to think twice, and admit to being human and making mistakes, hold onto her and give her the most you can. She may not be thinking about you every second of the day, but she will give you a part of her that she knows you can break—her heart. So don't hurt her, don't change her, don't analyze and don't expect more than she can give. Smile when she makes you happy, let her know when she makes you mad, and miss her when she's not there."},
 {'author': '//]]>',
  'tags': ['katniss', 'love', 'peeta', 'suzanne-collins', 'the-hunger-games'],
  'text': 'You love me. Real or not real?"I tell him, "Real.'},
 {'author': '//]]>',

**PANDAS**

In [ ]:
import pandas as pd

In [ ]:
import seaborn as sns

In [ ]:
df = sns.load_dataset("iris")

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [ ]:
df.index

RangeIndex(start=0, stop=150, step=1)

In [ ]:
df["sepal_length"]

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal_length, Length: 150, dtype: float64

In [ ]:
names = ["Anuj", "Ravi", "Mohit"]

In [ ]:
ages = [26, 34, 21]

In [ ]:
d = {
    "name" : names,
     "age" : ages
}

In [ ]:
d

{'age': [26, 34, 21], 'name': ['Anuj', 'Ravi', 'Mohit']}

In [ ]:
pd.DataFrame(d)

    name  age
0   Anuj   26
1   Ravi   34
2  Mohit   21

In [ ]:
import numpy as np

In [ ]:
data = np.random.randint(10, 20, (10, 5))

In [ ]:
pd.DataFrame(data)

    0   1   2   3   4
0  13  13  11  10  11
1  17  12  12  11  16
2  13  17  12  10  14
3  15  15  17  16  15
4  19  13  11  12  15
5  11  12  16  14  15
6  15  17  11  14  10
7  15  13  11  16  17
8  18  13  11  17  14
9  15  19  10  13  19

In [ ]:
pd.DataFrame(data, columns=["p", "c", "m", "e", "b"])

    p   c   m   e   b
0  13  13  11  10  11
1  17  12  12  11  16
2  13  17  12  10  14
3  15  15  17  16  15
4  19  13  11  12  15
5  11  12  16  14  15
6  15  17  11  14  10
7  15  13  11  16  17
8  18  13  11  17  14
9  15  19  10  13  19

In [ ]:
marks = pd.DataFrame(data, columns=["p", "c", "m", "e", "b"])

In [ ]:
marks["cs"] = 0

In [ ]:
marks

    p   c   m   e   b  cs
0  13  13  11  10  11   0
1  17  12  12  11  16   0
2  13  17  12  10  14   0
3  15  15  17  16  15   0
4  19  13  11  12  15   0
5  11  12  16  14  15   0
6  15  17  11  14  10   0
7  15  13  11  16  17   0
8  18  13  11  17  14   0
9  15  19  10  13  19   0

In [ ]:
df.values

array([[5.1, 3.5, 1.4, 0.2, 'setosa'],
       [4.9, 3.0, 1.4, 0.2, 'setosa'],
       [4.7, 3.2, 1.3, 0.2, 'setosa'],
       [4.6, 3.1, 1.5, 0.2, 'setosa'],
       [5.0, 3.6, 1.4, 0.2, 'setosa'],
       [5.4, 3.9, 1.7, 0.4, 'setosa'],
       [4.6, 3.4, 1.4, 0.3, 'setosa'],
       [5.0, 3.4, 1.5, 0.2, 'setosa'],
       [4.4, 2.9, 1.4, 0.2, 'setosa'],
       [4.9, 3.1, 1.5, 0.1, 'setosa'],
       [5.4, 3.7, 1.5, 0.2, 'setosa'],
       [4.8, 3.4, 1.6, 0.2, 'setosa'],
       [4.8, 3.0, 1.4, 0.1, 'setosa'],
       [4.3, 3.0, 1.1, 0.1, 'setosa'],
       [5.8, 4.0, 1.2, 0.2, 'setosa'],
       [5.7, 4.4, 1.5, 0.4, 'setosa'],
       [5.4, 3.9, 1.3, 0.4, 'setosa'],
       [5.1, 3.5, 1.4, 0.3, 'setosa'],
       [5.7, 3.8, 1.7, 0.3, 'setosa'],
       [5.1, 3.8, 1.5, 0.3, 'setosa'],
       [5.4, 3.4, 1.7, 0.2, 'setosa'],
       [5.1, 3.7, 1.5, 0.4, 'setosa'],
       [4.6, 3.6, 1.0, 0.2, 'setosa'],
       [5.1, 3.3, 1.7, 0.5, 'setosa'],
       [4.8, 3.4, 1.9, 0.2, 'setosa'],
       [5.0, 3.0, 1.6, 0.2, 'setosa'],
       [5.0, 3.4, 1.6, 0.4, 'setosa'],
       [5.2, 3.5, 1.5, 0.2, 'setosa'],
       [5.2, 3.4, 1.4, 0.2, 'setosa'],
       [4.7, 3.2, 1.6, 0.2, 'setosa'],
       [4.8, 3.1, 1.6, 0.2, 'setosa'],
       [5.4, 3.4, 1.5, 0.4, 'setosa'],
       [5.2, 4.1, 1.5, 0.1, 'setosa'],
       [5.5, 4.2, 1.4, 0.2, 'setosa'],
       [4.9, 3.1, 1.5, 0.2, 'setosa'],
       [5.0, 3.2, 1.2, 0.2, 'setosa'],
       [5.5, 3.5, 1.3, 0.2, 'setosa'],
       [4.9, 3.6, 1.4, 0.1, 'setosa'],
       [4.4, 3.0, 1.3, 0.2, 'setosa'],
       [5.1, 3.4, 1.5, 0.2, 'setosa'],
       [5.0, 3.5, 1.3, 0.3, 'setosa'],
       [4.5, 2.3, 1.3, 0.3, 'setosa'],
       [4.4, 3.2, 1.3, 0.2, 'setosa'],
       [5.0, 3.5, 1.6, 0.6, 'setosa'],
       [5.1, 3.8, 1.9, 0.4, 'setosa'],
       [4.8, 3.0, 1.4, 0.3, 'setosa'],
       [5.1, 3.8, 1.6, 0.2, 'setosa'],
       [4.6, 3.2, 1.4, 0.2, 'setosa'],
       [5.3, 3.7, 1.5, 0.2, 'setosa'],
       [5.0, 3.3, 1.4, 0.2, 'setosa'],
       [7.0, 3.2, 4.7, 1.4, 'versicolor'],
       [6.4, 3.2, 4.5, 1.5, 'versicolor'],
       [6.9, 3.1, 4.9, 1.5, 'versicolor'],
       [5.5, 2.3, 4.0, 1.3, 'versicolor'],
       [6.5, 2.8, 4.6, 1.5, 'versicolor'],
       [5.7, 2.8, 4.5, 1.3, 'versicolor'],
       [6.3, 3.3, 4.7, 1.6, 'versicolor'],
       [4.9, 2.4, 3.3, 1.0, 'versicolor'],
       [6.6, 2.9, 4.6, 1.3, 'versicolor'],
       [5.2, 2.7, 3.9, 1.4, 'versicolor'],
       [5.0, 2.0, 3.5, 1.0, 'versicolor'],
       [5.9, 3.0, 4.2, 1.5, 'versicolor'],
       [6.0, 2.2, 4.0, 1.0, 'versicolor'],
       [6.1, 2.9, 4.7, 1.4, 'versicolor'],
       [5.6, 2.9, 3.6, 1.3, 'versicolor'],
       [6.7, 3.1, 4.4, 1.4, 'versicolor'],
       [5.6, 3.0, 4.5, 1.5, 'versicolor'],
       [5.8, 2.7, 4.1, 1.0, 'versicolor'],
       [6.2, 2.2, 4.5, 1.5, 'versicolor'],
       [5.6, 2.5, 3.9, 1.1, 'versicolor'],
       [5.9, 3.2, 4.8, 1.8, 'versicolor'],
       [6.1, 2.8, 4.0, 1.3, 'versicolor'],
       [6.3, 2.5, 4.9, 1.5, 'versicolor'],
       [6.1, 2.8, 4.7, 1.2, 'versicolor'],
       [6.4, 2.9, 4.3, 1.3, 'versicolor'],
       [6.6, 3.0, 4.4, 1.4, 'versicolor'],
       [6.8, 2.8, 4.8, 1.4, 'versicolor'],
       [6.7, 3.0, 5.0, 1.7, 'versicolor'],
       [6.0, 2.9, 4.5, 1.5, 'versicolor'],
       [5.7, 2.6, 3.5, 1.0, 'versicolor'],
       [5.5, 2.4, 3.8, 1.1, 'versicolor'],
       [5.5, 2.4, 3.7, 1.0, 'versicolor'],
       [5.8, 2.7, 3.9, 1.2, 'versicolor'],
       [6.0, 2.7, 5.1, 1.6, 'versicolor'],
       [5.4, 3.0, 4.5, 1.5, 'versicolor'],
       [6.0, 3.4, 4.5, 1.6, 'versicolor'],
       [6.7, 3.1, 4.7, 1.5, 'versicolor'],
       [6.3, 2.3, 4.4, 1.3, 'versicolor'],
       [5.6, 3.0, 4.1, 1.3, 'versicolor'],
       [5.5, 2.5, 4.0, 1.3, 'versicolor'],
       [5.5, 2.6, 4.4, 1.2, 'versicolor'],
       [6.1, 3.0, 4.6, 1.4, 'versicolor'],
       [5.8, 2.6, 4.0, 1.2, 'versicolor'],
       [5.0, 2.3, 3.3, 1.0, 'versicolor'],
       [5.6, 2.7, 4.2, 1.3, 'versicolor'],
       [5.7, 3.0, 4.2, 1.2, 'versicolor'],
       [5.7, 2.9, 4.2, 1.3, 'versicolor'],
       [6.2, 2.9, 4.3, 1.3, 'versicolor'],
       [5.1, 2.5, 3.0, 1.1, 'versicolor'],
       [5.7, 2.8, 4.1, 1.3, 'versicolor'],
       [6.3, 3.3, 6.0, 2.5, 'virginica'],
       [5.8, 2.7, 5.1, 1.9, 'virginica'],
       [7.1, 3.0, 5.9, 2.1, 'virginica'],
       [6.3, 2.9, 5.6, 1.8, 'virginica'],
       [6.5, 3.0, 5.8, 2.2, 'virginica'],
       [7.6, 3.0, 6.6, 2.1, 'virginica'],
       [4.9, 2.5, 4.5, 1.7, 'virginica'],
       [7.3, 2.9, 6.3, 1.8, 'virginica'],
       [6.7, 2.5, 5.8, 1.8, 'virginica'],
       [7.2, 3.6, 6.1, 2.5, 'virginica'],
       [6.5, 3.2, 5.1, 2.0, 'virginica'],
       [6.4, 2.7, 5.3, 1.9, 'virginica'],
       [6.8, 3.0, 5.5, 2.1, 'virginica'],
       [5.7, 2.5, 5.0, 2.0, 'virginica'],
       [5.8, 2.8, 5.1, 2.4, 'virginica'],
       [6.4, 3.2, 5.3, 2.3, 'virginica'],
       [6.5, 3.0, 5.5, 1.8, 'virginica'],
       [7.7, 3.8, 6.7, 2.2, 'virginica'],
       [7.7, 2.6, 6.9, 2.3, 'virginica'],
       [6.0, 2.2, 5.0, 1.5, 'virginica'],
       [6.9, 3.2, 5.7, 2.3, 'virginica'],
       [5.6, 2.8, 4.9, 2.0, 'virginica'],
       [7.7, 2.8, 6.7, 2.0, 'virginica'],
       [6.3, 2.7, 4.9, 1.8, 'virginica'],
       [6.7, 3.3, 5.7, 2.1, 'virginica'],
       [7.2, 3.2, 6.0, 1.8, 'virginica'],
       [6.2, 2.8, 4.8, 1.8, 'virginica'],
       [6.1, 3.0, 4.9, 1.8, 'virginica'],
       [6.4, 2.8, 5.6, 2.1, 'virginica'],
       [7.2, 3.0, 5.8, 1.6, 'virginica'],
       [7.4, 2.8, 6.1, 1.9, 'virginica'],
       [7.9, 3.8, 6.4, 2.0, 'virginica'],
       [6.4, 2.8, 5.6, 2.2, 'virginica'],
       [6.3, 2.8, 5.1, 1.5, 'virginica'],
       [6.1, 2.6, 5.6, 1.4, 'virginica'],
       [7.7, 3.0, 6.1, 2.3, 'virginica'],
       [6.3, 3.4, 5.6, 2.4, 'virginica'],
       [6.4, 3.1, 5.5, 1.8, 'virginica'],
       [6.0, 3.0, 4.8, 1.8, 'virginica'],
       [6.9, 3.1, 5.4, 2.1, 'virginica'],
       [6.7, 3.1, 5.6, 2.4, 'virginica'],
       [6.9, 3.1, 5.1, 2.3, 'virginica'],
       [5.8, 2.7, 5.1, 1.9, 'virginica'],
       [6.8, 3.2, 5.9, 2.3, 'virginica'],
       [6.7, 3.3, 5.7, 2.5, 'virginica'],
       [6.7, 3.0, 5.2, 2.3, 'virginica'],
       [6.3, 2.5, 5.0, 1.9, 'virginica'],
       [6.5, 3.0, 5.2, 2.0, 'virginica'],
       [6.2, 3.4, 5.4, 2.3, 'virginica'],
       [5.9, 3.0, 5.1, 1.8, 'virginica']], dtype=object)

In [ ]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [ ]:
df.T

                 0       1       2    ...        147        148        149
sepal_length     5.1     4.9     4.7  ...        6.5        6.2        5.9
sepal_width      3.5       3     3.2  ...          3        3.4          3
petal_length     1.4     1.4     1.3  ...        5.2        5.4        5.1
petal_width      0.2     0.2     0.2  ...          2        2.3        1.8
species       setosa  setosa  setosa  ...  virginica  virginica  virginica

[5 rows x 150 columns]

In [ ]:
df.sort_index?

In [ ]:
marks.sort_index(axis=1)

    b   c  cs   e   m   p
0  11  13   0  10  11  13
1  16  12   0  11  12  17
2  14  17   0  10  12  13
3  15  15   0  16  17  15
4  15  13   0  12  11  19
5  15  12   0  14  16  11
6  10  17   0  14  11  15
7  17  13   0  16  11  15
8  14  13   0  17  11  18
9  19  19   0  13  10  15

In [ ]:
marks.sort_values?

In [ ]:
marks.sort_values(["e"])

    p   c   m   e   b  cs
0  13  13  11  10  11   0
2  13  17  12  10  14   0
1  17  12  12  11  16   0
4  19  13  11  12  15   0
9  15  19  10  13  19   0
5  11  12  16  14  15   0
6  15  17  11  14  10   0
3  15  15  17  16  15   0
7  15  13  11  16  17   0
8  18  13  11  17  14   0

In [ ]:
marks.iloc[:5, 1:3]

    c   m
0  13  11
1  12  12
2  17  12
3  15  17
4  13  11

*** Slicing***

In [ ]:
marks.iloc[:5]

    p   c   m   e   b  cs
0  13  13  11  10  11   0
1  17  12  12  11  16   0
2  13  17  12  10  14   0
3  15  15  17  16  15   0
4  19  13  11  12  15   0

In [ ]:
marks.iloc[:5, 1:]

    c   m   e   b  cs
0  13  11  10  11   0
1  12  12  11  16   0
2  17  12  10  14   0
3  15  17  16  15   0
4  13  11  12  15   0

In [ ]:
marks.iloc[::2]

    p   c   m   e   b  cs
0  13  13  11  10  11   0
2  13  17  12  10  14   0
4  19  13  11  12  15   0
6  15  17  11  14  10   0
8  18  13  11  17  14   0

In [ ]:
marks.iloc[0:10:2]

    p   c   m   e   b  cs
0  13  13  11  10  11   0
2  13  17  12  10  14   0
4  19  13  11  12  15   0
6  15  17  11  14  10   0
8  18  13  11  17  14   0

In [ ]:
marks.iloc[[0, 2, 6]]

    p   c   m   e   b  cs
0  13  13  11  10  11   0
2  13  17  12  10  14   0
6  15  17  11  14  10   0

In [ ]:
marks.iloc[[0, 2, 6], [0, 2, 3]]

    p   m   e
0  13  11  10
2  13  12  10
6  15  11  14

**Data -> DataFrames -> CSV**

In [ ]:
import pandas as pd

In [ ]:
pd.DataFrame(total)

                                                  text  ...                                               tags
0    I'm selfish, impatient and a little insecure. ...  ...  [attributed-no-source, best, life, love, mista...
1    You've gotta dance like there's nobody watchin...  ...  [dance, heaven, hurt, inspirational, life, lov...
2    You know you're in love when you can't fall as...  ...  [attributed-no-source, dreams, love, reality, ...
3    A friend is someone who knows all about you an...  ...              [friend, friendship, knowledge, love]
4    Darkness cannot drive out darkness: only light...  ...  [darkness, drive-out, hate, inspirational, lig...
..                                                 ...  ...                                                ...
145  You don't love someone because they're perfect...  ...                                  [imperfect, love]
146  There is nothing I would not do for those who ...  ...                                 [friendship, love]
147  If you can make a woman laugh, you can make he...  ...                [attributed-no-source, girls, love]
148  Love never dies a natural death. It dies becau...  ...                                      [death, love]
149  We’re all a little weird. And life is a little...  ...                                  [love, weirdness]

[150 rows x 3 columns]

In [ ]:
df = pd.DataFrame(total)

In [ ]:
df.to_csv("scrap.csv")

In [ ]:
df.to_csv("scrap.csv", index=None)